server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jbdcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://metaverse.ohgiraffers.com/comproject?serverTimezone=Asia/Seoul
    username: comproject
    password: comproject
    hikari:
      auto-commit: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: true

  # jpa config
  jpa:
      generate-ddl: false
      show-sql: true
      database: mysql
      properties:
        hibernate:
          format: true
